version: '2'
services:
  yarnevn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yarnevn
    restart: unless-stopped
    #volumes: 
    #  - 【本地路径】:/home/workerspace
    ports: 
      - "8080:8080"
    hostname: yarnevn
networks:
  node_net: 